name: Build and release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  OPENBLOCK_SKIP_LOCAL_DEPS: 1

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: HXBlock Desktop ${{ github.ref_name }}
          body: |
            ## Change Log (en)

            - **New feature**

                1. Feature 1.
                2. Feature 2.

            - **Fix bug**

                1. Bug 1.
                2. Bug 2.

            ## 更改日志 (zh-cn)

            - **新功能**

                1. 功能1。
                2. 功能2。

            - **修复错误**

                1. 错误1。
                2. 错误2。

  build-windows:
    needs: create-release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Npm Install
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          npm ci

      - name: Fetch external resources
        shell: bash
        run: git clone --depth=1 https://github.com/haoxuekeji/external-resources.git ../external-resources-v3

      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run publish

  build-mac:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Npm Install
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          npm ci

      - name: Fetch external resources
        run: git clone --depth=1 https://github.com/haoxuekeji/external-resources.git ../external-resources-v3

      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
          PYTHON_PATH: /usr/bin/python3
        run: npm run publish
